Blog/HahaBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('login/', include('apps.login.urls')),
    path('', include('apps.article.urls')),
]

Blog/apps/article/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import IndexView, CateViewList, ArticleView, AddNewArticle, UpdateArticle, DeleteArticle

app_name = 'article'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', IndexView.as_view(), name='search-result'),
    path('cate/<int:id_cate>', CateViewList.as_view(), name='cate-list'),
    path('detail/<int:id_article>', ArticleView.as_view(), name='article_detail'),
    path('update/<int:id_article>', UpdateArticle.as_view(), name='update_article'),
    path('delete/<int:id_article>', DeleteArticle.as_view(), name='delete_article'),
    path('new/', login_required(AddNewArticle.as_view(), login_url='/login/'), name='add-new'),
]

Blog/apps/login/urls.py
from django.urls import path, include
from .views import LoginClass, LogoutClass

app_name = 'login'
urlpatterns = [
    path('', LoginClass.as_view(), name='login-acc'),
    path('logout/', LogoutClass.as_view(), name='logout-acc'),
]

Blog/apps/user/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import  Registration_view, UserProfile, ChangePassword
app_name = 'user'
urlpatterns = [
    path('register/', Registration_view.as_view(), name='register'),
    path('<int:id_user>', login_required(UserProfile.as_view(), login_url='/login/'), name='profile'),
    path('change-password/<int:id_user>', login_required(ChangePassword.as_view(), login_url='/login/'), name='change-pass'),
]

Blog/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


# we use AbstractUser is base class to be applied by Django, it contain the base features of user
class UserProf(AbstractUser):
    sex_choice = ((0, "Female"), (1, 'Male'), (3, 'None'))
    age = models.IntegerField(default=0)
    sex = models.IntegerField(choices= sex_choice, default= 0)
    phone = models.CharField(default= '', max_length= 255)
    # avatar_img = models.ImageField(upload_to='')

Blog/apps/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProf

class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text="Required. Add a valid email address", required=True)
    class Meta:
        model = UserProf
        # UserProf is create User model of django,
        # UserProf will contain the fields: username,
        fields = ("username", "email", "password1", "password2", 'sex', 'age')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username_re', 'id': 'username_re'}),
            'email': forms.EmailInput(attrs={'class': 'email_re'}),
            'password1': forms.PasswordInput(attrs={'class': 'password-1'}),
            'password2': forms.PasswordInput(attrs={'class':'password-2'}),
            'age': forms.NumberInput(attrs={'class': 'age', 'id': 'age'})
        }


class UserProfileForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text="Required. Add a valid email address", required=True)
    class Meta:
        model = UserProf
        # UserProf is create User model of django,
        # UserProf will contain the fields: username,
        fields = ("username", "email", "first_name", "last_name", 'age', 'phone', 'sex')

Blog/apps/user/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib import messages
from .forms import NewUserForm, UserProfileForm
from .models import UserProf
from apps.article.models import Category, Article
from apps.login.until import norm_text
import pdb


# Create your views here.

class Registration_view(View):
    def get(self, request):
        form = NewUserForm()
        return render(request, 'homepage/user/registration.html', {'f': form})
    def post(self, request):
        form = NewUserForm(request.POST)
        # print(form)
        if form.is_valid():
            form.save()
            # u = form.username
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login:login-acc')
        return HttpResponse("can't create new account!")

class UserProfile(View):
    def get(self, request, id_user):
        user = UserProf.objects.get(pk=id_user)
        ls_arts = Article.objects.filter(id_user=user)
        categories = Category.objects.all()
        form = UserProfileForm(initial={
            'username':user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'age': user.age,
            'phone': user.phone,
            'sex': user.sex
        })
        context = {'form':form, 'cates':categories, 'articles': ls_arts}
        if (request.user.username == user.username) | (request.user.has_perm('user.change_userprof')):
            sex_choice = []
            for sex in ((0, "Female"), (1, 'Male'), (3, 'None')):
                if sex[0] == user.sex:
                    context['user_sex'] = {'idx': sex[0], 'type': sex[1]}
                sex_choice.append({'idx': sex[0], 'type': sex[1]})
            context['sex_choice'] = sex_choice
            return render(request, 'homepage/user/UserProfile.html', context)
        return render(request, 'homepage/user/UserProfile_for_Customer.html', context)
    def post(self, request, id_user):
        user = UserProf.objects.get(pk=id_user)
        user.first_name = norm_text(request.POST['first_name'])
        user.last_name = norm_text(request.POST['last_name'])
        user.phone = str(request.POST['phone']).strip()
        user.age = int(request.POST['age'])
        user.sex = int(request.POST['sex'])
        user.save()
        return redirect('user:profile', id_user=id_user)


class ChangePassword(View):
    def get(self, request, id_user):
        user = UserProf.objects.get(pk=id_user)
        if request.user.username == user.username:
            return render(request, 'homepage/user/ChangePassword.html', {'user': user})
        return redirect('user:profile', id_user=id_user)
    def post(self, request, id_user):
        user = UserProf.objects.get(pk=id_user)
        cur_pass = request.POST['current-pass']
        new_pass1 = request.POST['new-pass1']
        new_pass2 = request.POST['new-pass2']
        if user.check_password(cur_pass):  # check current password
            if new_pass1 == new_pass2:
                user.set_password(new_pass1)
                user.save()  # update new password
                return redirect('user:profile', id_user=id_user)
        return render(request, 'homepage/error/Error_pass.html', {'id_user':id_user})

Blog/templates/homepage/user/ChangePassword.html
{% extends 'homepage/base.html' %}

{% block content0 %}

    <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
    <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>

{% endblock %}


{% block content %}
    <h2>Registration Form</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="module aligned ">
            <div class="form-row res-username">
                <label class="required">Username: </label>
                <h3>{{ user.username }}</h3>
            </div>
            <div class="form-row current-pass">
                <label class="required">Current Password: </label>
                <input type="password" name="current-pass" id="id_old_pass">
            </div>

            <div class="form-row new-pass1">
                    <label class="required">New Password: </label>
                    <input type="password" name="new-pass1" id="id_new_pass1">
            </div>
            <div class="form-row new-pass2">
                    <label class="required">Repeat Password: </label>
                    <input type="password" name="new-pass2" id="id_new_pass2">
            </div>

            <div class="form-row res-term">
                    <button type="submit" class="registerbtn">Update</button>
            </div>
        </fieldset>
    </form>


    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}

Blog/templates/homepage/user/UserProfile.html
{% extends 'homepage/base.html' %}

{% block content0 %}

    {% for cate in cates %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
    <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>

{% endblock %}

{% block content %}
    <h2>{{ form.initial.username }}</h2>
    <div class="change-pass">
        <a href="{% url 'user:change-pass' user.id %}"><button>Change Password</button></a>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="user_infor">
            <fieldset class="module aligned ">
                <div class="form-row firstname">
                    <label class="required">First Name: </label>
                    <input type="text" name="first_name" maxlength="150" id="id_first_name" value="{{ form.initial.first_name }}">
                </div>
                <div class="form-row lastname">
                    <label class="required">Last Name: </label>
                    <input type="text" name="last_name" maxlength="150" id="id_last_name" value="{{ form.initial.last_name }}">
                </div>
                <div class="form-row res-email">
                    <label class="required">Email: </label>
<!--                    <input type="text" name="email" maxlength="150" id="id_email" value="{{ form.initial.email }}">-->
                    {{ form.initial.email }}
                </div>
                <div class="form-row res-phone">
                    <label class="required">Phone: </label>
                    <input type="text" name="phone" maxlength="150" id="id_phone" value="{{ form.initial.phone }}">
                </div>
                <div class="form-row res-age">
                    <label class="required">Age: </label>
                    <input type="text" name="age" maxlength="150" id="id_age" value="{{ form.initial.age }}">
                </div>
                <div class="form-row res-sex">
                    <label class="required">Sex: </label>
                    <input type="hidden" name="sex" maxlength="150" id="id_sex" value="{{ user_sex.idx }}">
                    <select id="id_sex_choice" onchange="changeValue_action()">
                        <option value="{{ user_sex.idx }}" selected disabled hidden>{{ user_sex.type }}</option>
                        {% for s_choice in sex_choice %}
                            <option value="{{ s_choice.idx }}" >{{ s_choice.type }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-row ">
                        <button type="submit" class="updateprofile">Save</button>
                </div>
            </fieldset>
        </div>
    </form>
    <h3>Articles:</h3>
    <ul>
        {% for article in articles %}
            <li>
                <a href="{% url 'article:article_detail' article.id %}"><h2>{{ article.title }}</h2></a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}

Blog/templates/homepage/user/UserProfile_for_Customer.html
{% extends 'homepage/base.html' %}

{% block content0 %}

    {% for cate in cates %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
    <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>

{% endblock %}

{% block content %}

    <form action="" method="GET">
        {% csrf_token %}
        <div class="user_infor">
            <h2>{{ form.initial.username }}</h2>
            <div class="form-row res-email">
                <label class="required">Email: </label>
                {{ form.initial.email }}
            </div>
        </div>
    </form>
    <h3>Articles:</h3>
    <ul>
        {% for article in articles %}
            <li>
                <a href="{% url 'article:article_detail' article.id %}"><h2>{{ article.title }}</h2></a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}

Blog/templates/homepage/user/registration.html
{% extends 'homepage/base.html' %}

{% block content %}
    <h2>Registration Form</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="module aligned ">
            <div class="form-row res-username">
                    <label class="required">Username: </label>
                    {{ f.username }}
            </div>
            <div class="form-row res-email">
                    <label class="required">Email: </label>
                    {{ f.email }}
            </div>
            <div class="form-row res-pass1">
                    <label class="required">Password: </label>
                    {{ f.password1 }}
            </div>
            <div class="form-row res-pass2">
                    <label class="required">Repeat Password: </label>
                    {{ f.password2 }}
            </div>
            <div class="form-row res-age">
                    <label class="required">Age: </label>
                    {{ f.age }}
            </div>
            <div class="form-row res-sex">
                    <label class="required">Sex: </label>
                    {{ f.sex }}
            </div>

            <div class="form-row res-term">
                    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
                    <button type="submit" class="registerbtn">Register</button>
            </div>
            <div class="container signin">
                <p>Already have an account? <a href="{% url 'login:login-acc' %}">Log in</a>.</p>
            </div>

        </fieldset>
    </form>


    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}