Blog/HahaBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('login/', include('apps.login.urls')),
    path('', include('apps.article.urls')),
]

Blog/apps/article/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import IndexView, CateViewList, ArticleView, AddNewArticle, UpdateArticle, DeleteArticle

app_name = 'article'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', IndexView.as_view(), name='search-result'),
    path('cate/<int:id_cate>', CateViewList.as_view(), name='cate-list'),
    path('detail/<int:id_article>', ArticleView.as_view(), name='article_detail'),
    path('update/<int:id_article>', UpdateArticle.as_view(), name='update_article'),
    path('delete/<int:id_article>', DeleteArticle.as_view(), name='delete_article'),
    path('new/', login_required(AddNewArticle.as_view(), login_url='/login/'), name='add-new'),
]

Blog/apps/login/urls.py
from django.urls import path, include
from .views import LoginClass, LogoutClass

app_name = 'login'
urlpatterns = [
    path('', LoginClass.as_view(), name='login-acc'),
    path('logout/', LogoutClass.as_view(), name='logout-acc'),
]

Blog/apps/user/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import  Registration_view, UserProfile, ChangePassword
app_name = 'user'
urlpatterns = [
    path('register/', Registration_view.as_view(), name='register'),
    path('<int:id_user>', login_required(UserProfile.as_view(), login_url='/login/'), name='profile'),
    path('change-password/<int:id_user>', login_required(ChangePassword.as_view(), login_url='/login/'), name='change-pass'),
]

Blog/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Haha</title>
        <link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'homepage/css/forms.css' %}">

    </head>
    <body>
        <div class="header">
            <h1>My Haha</h1>
        </div>
        <div class="menu">
             <ul>
                 <li><a href="{% url 'article:index' %}" style="color:white">Home</a></li>
                <!--        menu         -->
                 {% block content0 %}
                 {% endblock %}
            </ul>

        </div>
        <!--  search      -->
        <div class="search-bar">
            {% block content01 %}
            {% endblock %}
        </div>
        <!--  main content      -->
        <div class="content_detail">
            {% block content %}
            {% endblock %}
        </div>
        <!--  sub content      -->
        <div class="another_content">
            {% block content1 %}
            {% endblock %}
        </div>
    <script src="{% static 'homepage/js/main.js' %}"></script>
    <script src="{% static 'homepage/js/change_value_Profile.js' %}"></script>
    </body>

</html>

Blog/templates/homepage/index.html
{% extends 'homepage/base.html' %}

<!-- Menu: Navigation Bar-->
{% block content0 %}

    {% for cate in categories %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    {% if user.username %}
        <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
        <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>
    {% else %}
        <li><a href="{% url 'user:register' %}" style="color:white">Sign In</a></li>
        <li><a href="{% url 'login:login-acc' %}" style="color:white">Log In</a></li>
    {% endif %}


{% endblock %}

<!-- search -->
{% block content01 %}
    <form action="" method="POST">
        {% csrf_token %}
        <div >
            <fieldset class="module aligned ">
                <input type="text" placeholder="Search.." name="search_value">
                <input type="submit" value="Search">
            </fieldset>
        </div>
    </form>

{% endblock %}
<!-- main Content-->
{% block content %}
    <h3>News:</h3>
    <ul>
        {% for article in articles %}
            <li>
                <a href="{% url 'article:article_detail' article.id %}"><h2>{{ article.title }}</h2></a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'article:add-new' %}"><button>Add New</button></a>
{% endblock %}

{% block content1 %}

{% endblock %}