Blog/HahaBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls')),
    path('login/', include('apps.login.urls')),
    path('', include('apps.article.urls')),
]

Blog/apps/article/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import IndexView, CateViewList, ArticleView, AddNewArticle, UpdateArticle, DeleteArticle

app_name = 'article'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', IndexView.as_view(), name='search-result'),
    path('cate/<int:id_cate>', CateViewList.as_view(), name='cate-list'),
    path('detail/<int:id_article>', ArticleView.as_view(), name='article_detail'),
    path('update/<int:id_article>', UpdateArticle.as_view(), name='update_article'),
    path('delete/<int:id_article>', DeleteArticle.as_view(), name='delete_article'),
    path('new/', login_required(AddNewArticle.as_view(), login_url='/login/'), name='add-new'),
]

Blog/apps/login/urls.py
from django.urls import path, include
from .views import LoginClass, LogoutClass

app_name = 'login'
urlpatterns = [
    path('', LoginClass.as_view(), name='login-acc'),
    path('logout/', LogoutClass.as_view(), name='logout-acc'),
]

Blog/apps/user/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import  Registration_view, UserProfile, ChangePassword
app_name = 'user'
urlpatterns = [
    path('register/', Registration_view.as_view(), name='register'),
    path('<int:id_user>', login_required(UserProfile.as_view(), login_url='/login/'), name='profile'),
    path('change-password/<int:id_user>', login_required(ChangePassword.as_view(), login_url='/login/'), name='change-pass'),
]

Blog/apps/article/models.py
from django.db import models
from django.utils import timezone
from apps.user.models import UserProf

# Create your models here.

class Category(models.Model):
    #  null=False and blank=False, this field is not allowed to be null and blank (default= False)
    name_cate = models.CharField(max_length=100, null=False, blank=False)
    def __str__(self):
        return self.name_cate

class SubCategory(models.Model):
    #  name of sub-cate
    name_cate = models.CharField(max_length=100)
    def __str__(self):
        return self.name_cate

class Article(models.Model):
    title = models.CharField(max_length=512)
    content = models.TextField(null=False, blank=False)
    published = models.DateField(default= timezone.datetime.now)
    #  on_delete=models.DO_NOTHING is as like on_delete=models.CASCADE
    # models.DO_NOTHING: we can't remove parents object, when children object does exit
    # models.CASCADE: when we remove parents object, children object will be removed
    id_cate = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, default=None)
    id_sub_cate = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True, default=None)
    id_user = models.ForeignKey(UserProf, on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return self.title

class Comment(models.Model):
    id_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    id_user = models.ForeignKey(UserProf, on_delete=models.CASCADE, default=None)
    content = models.CharField(max_length=1000)
    published = models.DateField(default=timezone.datetime.now)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.content

class SubComment(models.Model):
    id_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    published = models.DateField(default=timezone.datetime.now)
    def __str__(self):
        return self.content

Blog/apps/article/forms.py
from django import forms
from .models import Article, Comment, Category, SubCategory
from apps.user.models import UserProf

# way 1: create form don't use model
# class ArticleForm(forms.ModelForm):
#     choice_cate = Category.objects.all()
#     choice_sub_cate = SubCategory.objects.all()
#     users = UserProf.objects.all()
#     title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'title_detail', 'id': 'id_title'}))
#     content =  forms.CharField(max_length=100, widget=forms.Textarea(attrs={'class': 'content-art'}))
#     published =  forms.DateField(widget=forms.DateInput(format=('%m/%d/%Y'), attrs={'class': 'date-time'}))
#     id_cate=  forms.ChoiceField(choices=choice_cate)
#     id_sub_cate = forms.ChoiceField(choices=choice_sub_cate)
#     id_user = forms.ChoiceField(choices=users, widget=forms.TextInput(attrs={'class': 'author'}))

# way 2: Aticle Form use model
class AddArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'published', 'id_cate', 'id_sub_cate', 'id_user')

        # add widgets for model form type and create attributes for the each tag to contain data
        widgets = {
            'title': forms.TextInput(attrs={'class': 'title_detail', 'id': 'id_title'}),
            'content': forms.Textarea(attrs={'class': 'content-art'}),
            'published': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'date-time'}),
            'id_user': forms.HiddenInput(attrs={'class': 'user_detail'})
        }

class UpdateArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'id_cate', 'id_sub_cate')
        # add widgets for model form type and create attributes for the each tag to contain data
        widgets = {
            'title': forms.TextInput(attrs={'class': 'title_detail', 'id': 'id_title'}),
            'content': forms.Textarea(attrs={'class': 'content-art'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('id_article', 'id_user', 'content')
        # add widgets for model form type and create attributes for the each tag to contain data
        widgets = {
            'id_article': forms.HiddenInput(attrs={'class': 'article_'}),
            'id_user': forms.HiddenInput(attrs={'class': 'user_cmt'}),
            'content': forms.TextInput(attrs={'class': 'content-art'})
        }

Blog/apps/article/views.py
import pdb
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from .models import Article, Category, SubCategory, Comment
from .forms import AddArticleForm, CommentForm, UpdateArticleForm
from apps.user.models import UserProf
from apps.login.until import login_action, norm_text


# Create your views here.


#  category list
categories = Category.objects.all()


class IndexView(View):
    def get(self, request):
        #  get first 5 artilces in database
        ls_article = Article.objects.all()[:5]
        context = {'articles': ls_article, 'categories': categories}
        #  check login status of client
        user = login_action(request)
        context['user'] = user
        # print('login action: ', context)
        return render(request, 'homepage/index.html', context)
    def post(self, request):
        query_value = norm_text(request.POST['search_value'])
        if query_value != '':
            # pdb.set_trace()
            result = Article.objects.filter(title__icontains=query_value)
            context = {'articles': result, 'categories': categories, 'user': login_action(request)}
            return render(request, 'homepage/article/search_result.html', context)
        else:
            return redirect('article:index')


class CateViewList(View):
    def get(self, request, id_cate):
        cate = Category.objects.get(pk=id_cate)
        #  get first 5 artilces in database
        article = Article.objects.filter(id_cate=cate)[:5]
        context = {'articles': article}

        context['categories'] = categories
        #  check login status of client
        user = login_action(request)
        context['user'] = user
        return render(request, 'homepage/article/cates_list.html', context)


class ArticleView(View):
    def get(self, request, id_article):
        #  get first 5 artilces in database
        article = Article.objects.get(pk=id_article)
        ls_comments = Comment.objects.filter(id_article=id_article)
        initial = { 'id_article': article }
        if request.user.is_authenticated: # check login
            initial['id_user'] =  UserProf.objects.get(pk=request.user.id)
        else:
            initial['id_user'] = None
        comt_form = CommentForm(initial= initial)
        context = {'article': article, 'categories': categories, 'user': login_action(request), 'cmts':ls_comments, 'cmt_f':comt_form}

        # print the whole permisstions of user:
        # print(request.user.get_all_permissions())

        #  check if user is author or super-user, user can update or delete article
        if (request.user.username == article.id_user.username) | (request.user.has_perm('article.change_article')):
            context['update'] = 1
        if (request.user.username == article.id_user.username) | (request.user.has_perm('article.delete_article')):
            context['delete'] = 1
        return render(request, 'homepage/article/article_detail.html', context)
    def post(self, request, id_article):
        if request.user.is_authenticated:  # check login
            pdb.set_trace()
            cmt = CommentForm(request.POST)
            if cmt.is_valid():
                cmt.save()
                return redirect('article:article_detail', id_article=id_article)
            return render(request, 'homepage/error/Error_cmt.html', {'id_article':id_article})
        else:
            return redirect('login:login-acc')


class AddNewArticle(View):
    def get(self, request):
        initial ={
            'id_user': UserProf.objects.get(pk=request.user.id)
        }
        form = AddArticleForm(initial=initial)
        context = {'form': form}
        return render(request, 'homepage/article/add_article.html', context)

    def post(self, request):
        data = AddArticleForm(request.POST)
        #  get data of the each input tag during name attributes to save a varibale
        if data.is_valid():
            #  save the data object to db
            data.save()
            article = Article.objects.get(title=data.data['title'])
            return redirect('article:article_detail', id_article=article.id)
        return render(request, 'homepage/error/Error_add.html')

    def put(self, request):
        pass

class UpdateArticle(View):
    def get(self, request, id_article):
        article = Article.objects.get(pk=id_article)
        #  check if user is author or super-user, user can update or delete article
        if (request.user.username == article.id_user.username) | (request.user.has_perm('article.change_article')):
            form = UpdateArticleForm(initial={
                'title': article.title,
                'content': article.content,
                'id_cate': article.id_cate,
                'id_sub_cate': article.id_sub_cate
            })
            context = {'article': article, 'form': form, 'cates':categories, 'sub_cates': SubCategory.objects.all()}
            return render(request, 'homepage/article/update_article.html', context)
        else:
            return render(request, 'homepage/error/Error_permission.html', {'id_article': id_article})
    def post(self, request, id_article):
        article = Article.objects.get(pk=id_article)
        article.title = norm_text(request.POST['title'])
        article.content = request.POST['content']
        if  article.id_cate.id != int(request.POST['id_cate']):
            article.id_cate = Category.objects.get(pk=request.POST['id_cate'])
        if article.id_sub_cate.id != int(request.POST['id_sub_cate']):
            article.id_sub_cate = SubCategory.objects.get(pk=request.POST['id_sub_cate'])
        article.save(force_update=True)
        return redirect('article:article_detail', id_article=id_article)

class DeleteArticle(View):
    def get(self, request, id_article):
        article = Article.objects.get(pk=id_article)
        if (request.user.username == article.id_user.username) | (request.user.has_perm('article.delete_article')):
            return render(request, 'homepage/article/delete_article.html', {'article': article})
        else:
            return render(request, 'homepage/error/Error_permission.html', {'id_article': id_article})
    def post(self, request, id_article):
        article = Article.objects.get(pk=id_article)
        if request.POST['delete'] == 'Yes':
            article.delete()
            return redirect('article:index')
        return redirect('article:article_detail', id_article=id_article)

Blog/templates/homepage/article/add_article.html
{% extends 'homepage/base.html' %}

{% block content %}
    <h1>Add New Article:</h1>
    <form action="{% url 'article:add-new' %}" method="POST">
        {% csrf_token %}
        <div >
            <fieldset class="module aligned ">
                <div class="form-row field-title">
                    <label class="required">Title: </label>
                    {{ form.title }}
                </div>
                <div class="form-row field-content">
                    <label class="required">Content: </label>
                    {{ form.content }}
                </div>
                <div class="form-row field-time">
                    <label class="required">Time: </label>
                    {{ form.published }}
                </div>
                <div class="form-row field-cate">
                    <label class="required">Category: </label>
                    {{ form.id_cate }}
                </div>
                <div class="form-row field-sud-cate">
                    <label class="required">Sub Category: </label>
                    {{ form.id_sub_cate }}
                </div>
                <div class="form-row field-user">
                    {{ form.id_user }}
                </div>

                <input type="submit" value="save">
            </fieldset>
        </div>
    </form>

    <a href="{% url 'article:index' %}">Back</a>

{% endblock %}

Blog/templates/homepage/article/article_detail.html
{% extends 'homepage/base.html' %}
<!-- input tag: 
        + type:
            - radio: vote
            - submit: send data from form
            - ...
        + value: value from dev
        + name (neu ko dung phuong thuc name user co the vote nhieuf value 1 luc)
            - choice: chi cho phep dc 1 vote gia tri 
            
-->
{% block content0 %}

    {% for cate in categories %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    {% if user.username %}
        <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
        <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>
    {% else %}
        <li><a href="{% url 'user:register' %}" style="color:white">Sign In</a></li>
        <li><a href="{% url 'login:login-acc' %}" style="color:white">Log In</a></li>
    {% endif %}
{% endblock %}

{% block content %} 
    {% if article %}
        <h2>{{ article.title }}</h2>
        <div>
                <time class="published">{{ article.published }}</time>
        </div>
        <div>
                <span class="cate-art">
                    <a href="{% url 'article:cate-list' article.id_cate.id %}">{{ article.id_cate.name_cate }}</a>
                    | {{ article.id_sub_cate.name_cate }}
                </span>
        </div>

        <form action="" method="GET">
            <!-- automatic to create token -->
            <!-- token duoc su dung de bao mat khi gui du lieu tu web vao DB
                moi lan chay se tu sinh 1 token moi -->
            {% csrf_token %}
            <p>{{ article.content }}</p>
        </form>
        <div class="author">
            {{ article.id_user }}
        </div>

    {% else %}
        <h3 style="color: red;">This question does't exist!!!</h3>
    {% endif %}
    <a href="{% url 'article:index' %}">Back</a>
    {% if update %}
        <a href="{% url 'article:update_article' article.id %}">Update</a>
    {% endif %}
    {% if update %}
        <a href="{% url 'article:delete_article' article.id %}">Delete</a>
    {% endif %}
{% endblock %}

{% block content1 %}
    <h4>Your Comment:</h4>
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <div class="form-row field-cmt-content">
                {{ cmt_f.content }}
                {{ cmt_f.id_user }}
                {{ cmt_f.id_article }}
                <input type="submit" value="Add Comment">
            </div>
        </div>
    </form>
    <h4>Comments:</h4>
    <form action="" method="POST">
            <!-- automatic to create token -->
            <!-- token duoc su dung de bao mat khi gui du lieu tu web vao DB
                moi lan chay se tu sinh 1 token moi -->
            {% csrf_token %}
            {% if cmts %}
                {% for cmt in cmts %}
                    <div>
                        <b>{{ cmt.id_user }}:</b><span>{{ cmt.content }}</span>
                    </div>
                {% endfor %}
            {% endif %}

        </form>


{% endblock %}

Blog/templates/homepage/article/cates_list.html
{% extends 'homepage/base.html' %}
<!-- input tag: 
        + type:
            - radio: vote
            - submit: send data from form
            - ...
        + value: value from dev
        + name (neu ko dung phuong thuc name user co the vote nhieuf value 1 luc)
            - choice: chi cho phep dc 1 vote gia tri 
            
-->

{% block content0 %}

    {% for cate in categories %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    {% if user.username %}
        <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
        <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>
    {% else %}
        <li><a href="{% url 'user:register' %}" style="color:white">Sign In</a></li>
        <li><a href="{% url 'login:login-acc' %}" style="color:white">Log In</a></li>
    {% endif %}
{% endblock %}


{% block content %} 
    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'article:article_detail' article.id %}"><h2>{{ article.title }}</h2></a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <h3 style="color: red;">This question does't exist!!!</h3>
    {% endif %}
    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}

Blog/templates/homepage/article/delete_article.html
{% extends 'homepage/base.html' %}

<!-- main Content-->
{% block content %}
    <h3>Do you want to delete the article: <a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a></h3>
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <input type="submit" value="Yes" name="delete">
            <input type="submit" value="Cancel" name="delete">
        </div>
    </form>
    <a href="{% url 'article:article_detail' article.id %}">Back</a>
{% endblock %}

Blog/templates/homepage/article/search_result.html
{% extends 'homepage/base.html' %}

{% block content0 %}

    {% for cate in categories %}
        <li><a href="{% url 'article:cate-list' cate.id %}" style="color:white">{{ cate.name_cate }}</a></li>
    {% endfor %}
    {% if user.username %}
        <li><a href="{% url 'user:profile' user.id %}" style="color:white">{{ user.username }}</a></li>
        <li><a href="{% url 'login:logout-acc' %}" style="color:white">Log Out</a></li>
    {% else %}
        <li><a href="{% url 'user:register' %}" style="color:white">Sign In</a></li>
        <li><a href="{% url 'login:login-acc' %}" style="color:white">Log In</a></li>
    {% endif %}
{% endblock %}


{% block content %} 
    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'article:article_detail' article.id %}"><h2>{{ article.title }}</h2></a>
                </li>
            {% endfor %}
        </ul>

    {% else %}
        <h3 style="color: red;">This question does't exist!!!</h3>
    {% endif %}
    <a href="{% url 'article:index' %}">Back</a>
{% endblock %}

Blog/templates/homepage/article/update_article.html
{% extends 'homepage/base.html' %}

{% block content %}
    <h1>Edit Article:</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div >
            <fieldset class="module aligned ">
                <div class="form-row field-title">
                    <label class="required">Title: </label>
                    <input type="text" name="title"  maxlength="512" required="" id="id_title" value="{{ form.initial.title }}">
                </div>
                <div class="form-row field-content">
                    <label class="required">Content: </label>
                    <textarea name="content" cols="40" rows="10" required="" id="id_content">{{ form.initial.content }}</textarea>
                </div>
                <div class="form-row field-cate">
                    <label class="required">Category: </label>
                    <input type="hidden" id="cate" name="id_cate" class="vTextField" value="{{ form.initial.id_cate.id }}">
                    <select id="cates" onchange="moveContentFromSelectToInputTag()">
                        <option value="{{ form.initial.id_cate.id }}">{{ form.initial.id_cate.name_cate }}</option>
                        {% for cate in cates %}
                            <option value="{{ cate.id }}">{{ cate.name_cate }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-row field-sud-cate">
                    <label class="required">Sub Category: </label>
                    <input type="hidden" id="sub-cate" name="id_sub_cate" class="vTextField" value="{{ form.initial.id_sub_cate.id }}">
                    <select id="sub-cates" onchange="moveContentFromSelectToInputTag()">
                        <option value="{{ form.initial.id_sub_cate.id }}" selected disabled hidden>{{ form.initial.id_sub_cate.name_cate }}</option>
                        {% for s_cate in sub_cates %}
                            <option value="{{ s_cate.id }}">{{ s_cate.name_cate }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- submit button -->
                <input type="submit" value="Update">
            </fieldset>
        </div>
    </form>

    <a href="{% url 'article:article_detail' article.id %}">Back</a>

{% endblock %}